{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "falconpi.fullname" . }}
  labels: {{- include "falconpi.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
{{- end }}